config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :projects do
  member do
    get "vote"
  end
end

  resources :utterances do
  member do
    get "vote"
  end
end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "projects#index"

  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :utterances, dependent: :destroy
  acts_as_votable 

  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  # before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]
  
  before_filter :require_user_signed_in

  before_action :set_project, only: [:show, :edit, :update, :destroy, :vote]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @project.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:user_id, :title)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project, :html => { :class => 'form-horizontal form-model' } do |f|
  .form-group
    = f.label :title, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_field :title, :class => 'text-field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), |
        projects_path, :class => 'btn btn-default'                   |

app/views/projects/_project_utterances.html.haml
%section#audio

- @project.utterances.each do |ut|
  .utterance
    %label 
      = link_to ut.wav, ut.wav_url
      %audio{controls: "controls", source: URI.join(request.url,ut.wav_url)}
      = link_to "destroy", ut, method: :delete
    
      

app/views/projects/edit.html.haml
- model_class = Project
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Project
= render :partial => 'form'

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => Project %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.id %></td>
        <td><%= project.title %></td>
        <td><%=l project.created_at, format: :long %></td>
        <td>
          <%= link_to project_path(project), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to project_path(project), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Project %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.haml
- model_class = Project
.page-header
  %h1= t '.title', :default => @project.title

.div
  %label Utterances
  = render partial: 'project_utterances'
  
.div
  = form_for Utterance.new, html: {id: "fileupload"} do |f|
    = f.file_field :wav, multiple: true, name: "utterance[wav]"
    = f.hidden_field :project_id, value: @project.id
  #progress  
    .label
    .bar{style: "width: 0%;"}


.form-group
  = link_to t('.back', :default => t("helpers.links.back")), |
    projects_path, :class => 'btn btn-default'               |
  -#
  = link_to t('.edit', :default => t("helpers.links.edit")), |
    edit_project_path(@project), :class => 'btn btn-default' |
  -#
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    project_path(@project),                                                                                      |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |