config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :projects do
  member do
    get "vote"
  end
end

  resources :utterances do
  member do
    get "vote"
  end
end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "projects#index"

  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/utterance.rb
class Utterance < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  acts_as_votable 

  attr_accessor :transcription
  
  mount_uploader :wav, WavUploader

  # has_attached_file :wav, :processors => [:silence_detection, :mfcc_extraction]

  # before_post_process :skip_for_invalid

  # def skip_for_invalid
  #   true
  #   #return false if the attarchment is invalid. 
  # end

  # validates :wav, :attachment_content_type => { :content_type => ['audio/x-wav', 'audio/wav' ]}
end

app/controllers/utterances_controller.rb
class UtterancesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_utterance, only: [:show, :edit, :update, :destroy, :vote]

  # GET /utterances
  # GET /utterances.json
  def index
    @utterances = Utterance.all
  end

  # GET /utterances/1
  # GET /utterances/1.json
  def show
  end

  # GET /utterances/new
  def new
    @utterance = Utterance.new
  end

  # GET /utterances/1/edit
  def edit
  end

  # POST /utterances
  # POST /utterances.json
  def create
    @utterance = Utterance.new(utterance_params)
    @utterance.user = current_user

    respond_to do |format|
      if @utterance.save
        format.html { redirect_to @utterance, notice: 'Utterance was successfully created.' }
        format.json { render :show, status: :created, location: @utterance }
      else
        format.html { render :new }
        format.json { render json: @utterance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /utterances/1
  # PATCH/PUT /utterances/1.json
  def update
    respond_to do |format|
      if @utterance.update!(utterance_params)
        format.html { redirect_to @utterance, notice: 'Utterance was successfully updated.' }
        format.json { render :show, status: :ok, location: @utterance }
      else
        format.html { render :edit }
        format.json { render json: @utterance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /utterances/1
  # DELETE /utterances/1.json
  def destroy
    @utterance.destroy
    respond_to do |format|
      format.html { redirect_to project_url(@utterance.project), notice: 'Utterance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @utterance.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_utterance
      @utterance = Utterance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def utterance_params
      params.require(:utterance).permit(:user_id, :project_id, :wav)
    end
end

app/helpers/utterances_helper.rb
module UtterancesHelper
end

app/views/utterances/_form.html.erb
<%= form_for @utterance, :html => { :class => 'form-horizontal form-model', :multipart => true } do |f| %>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
 	  <%= f.file_field :wav %>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  utterances_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/utterances/edit.html.erb
<%- model_class = Utterance -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Utterance %></h1>
</div>
<%= render :partial => 'form' %>

app/views/utterances/index.html.erb
<%- model_class = Utterance -%>
<div class="page-header">
  <h1><%=t '.title', :default => Utterance %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @utterances.each do |utterance| %>
      <tr>
        <td><%= utterance.id %></td>
        <td><%=l utterance.created_at, format: :long %></td>
        <td>
          <%= link_to utterance_path(utterance), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to utterance_path(utterance), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_utterance_path,
            :class => 'btn btn-primary' %>

app/views/utterances/new.html.erb
<%- model_class = Utterance -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Utterance %></h1>
</div>
<%= render :partial => 'form' %>

app/views/utterances/show.html.erb
<%- model_class = Utterance -%>
<div class="page-header">
  <h1><%=t '.title', :default => Utterance %></h1>
</div>


<div class="fieldset">
  <dl>FILENAME: <%= @utterance.wav_file_name %>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              utterances_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_utterance_path(@utterance), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              utterance_path(@utterance),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>